name: Generate snake animation

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: Platane/snk@v3
        id: snake-svg
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/upload-artifact@v4
        with:
          name: snake-svg
          path: dist/
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Generate snake animation'
          file_pattern: dist/
